Added preference panel to adjust hexagon radius and ripple size
moebrowne/hexplosion pull request #2
Opened 2024-10-05 16:55 UTC by vasutomar

Added a preferences panel to adjust ripple size and hexagon radius

![image](https://github.com/user-attachments/assets/73fb05ff-8cc6-400f-8e96-c25a878ce416)

2024-10-07 17:59 UTC, moebrowne requested changes
Thanks for the PR :rocket:

I've added a couple of comments of things which need adjusting

2024-10-07 17:59 UTC, moebrowne commented on index.html
> +            width: 8rem;
When different fonts are loaded the text can overflow.
![Screenshot from 2024-10-07 18-55-00](https://github.com/user-attachments/assets/55fed6f0-4e94-470f-a600-eb833caec1e6)

Please can you remove the fixed width, perhaps add some padding instead.

2024-10-07 17:59 UTC, moebrowne commented on index.html
> +              <input id="radius" placeholder="Hexagon size" />
Could we add default values to the inputs, when it loads they are empty but it obviously still works.

2024-10-20 05:45 UTC, vasutomar commented
Hello, I have made the requested changes.
Thanks

2024-10-22 18:02 UTC, merged

2024-10-22 18:02 UTC, moebrowne commented
Thanks!